/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JOptionPane;

/**
 *
 * @author Mertcan
 */
public class Oyun2 extends javax.swing.JFrame {

    /**
     * Creates new form Arayüz
     */
    static String ad1,ad2,ad3,ad4,ad5,ad6,ad7,ad8;
    static String ed1,ed2,ed3,ed4,ed5,ed6,ed7,ed8;
    static String bd1,bd2,bd3,bd4,bd5,bd6,bd7,bd8;
    static String r1,r2,r3,r4;
    static String R1,R2,R3,R4;
    int sayi = 0;
    int say1=0;
    int puan1=0;
    int puan2=0;
    int tik=0;
    
    
    public Oyun2() {
        initComponents();
        OrtayaK1.setVisible(false);
        OrtayaK2.setVisible(false);
       FutbolcuK1.setEnabled(false);
        FutbolcuK2.setEnabled(false);
        FutbolcuK3.setEnabled(false);
        FutbolcuK4.setEnabled(false);
        FutbolcuB1.setEnabled(false);
        FutbolcuB2.setEnabled(false);
        FutbolcuB3.setEnabled(false);
        FutbolcuB4.setEnabled(false);
        FutbolcuB4.setEnabled(false);
        FutbolcuB5.setEnabled(false);
        FutbolcuB6.setEnabled(false);
        FutbolcuB7.setEnabled(false);
        FutbolcuB8.setEnabled(false);
        BasketbolcuK1.setEnabled(false);
        BasketbolcuK2.setEnabled(false);
        BasketbolcuK3.setEnabled(false);
        BasketbolcuK4.setEnabled(false);
        BasketbolcuB1.setEnabled(false);
        BasketbolcuB2.setEnabled(false);
        BasketbolcuB3.setEnabled(false);
        BasketbolcuB4.setEnabled(false);
        BasketbolcuB5.setEnabled(false);
        BasketbolcuB6.setEnabled(false);
        BasketbolcuB7.setEnabled(false);
        BasketbolcuB8.setEnabled(false);
        Başla.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        KapatmaTuşu = new javax.swing.JButton();
        FutbolcuB5 = new javax.swing.JButton();
        FutbolcuB6 = new javax.swing.JButton();
        FutbolcuB7 = new javax.swing.JButton();
        FutbolcuB8 = new javax.swing.JButton();
        BasketbolcuB5 = new javax.swing.JButton();
        BasketbolcuB6 = new javax.swing.JButton();
        BasketbolcuB7 = new javax.swing.JButton();
        BasketbolcuB8 = new javax.swing.JButton();
        FutbolcuK1 = new javax.swing.JButton();
        FutbolcuK2 = new javax.swing.JButton();
        FutbolcuK3 = new javax.swing.JButton();
        FutbolcuK4 = new javax.swing.JButton();
        FutbolcuB4 = new javax.swing.JButton();
        FutbolcuB3 = new javax.swing.JButton();
        FutbolcuB2 = new javax.swing.JButton();
        FutbolcuB1 = new javax.swing.JButton();
        BasketbolcuK1 = new javax.swing.JButton();
        BasketbolcuK2 = new javax.swing.JButton();
        BasketbolcuK3 = new javax.swing.JButton();
        BasketbolcuK4 = new javax.swing.JButton();
        BasketbolcuB1 = new javax.swing.JButton();
        BasketbolcuB2 = new javax.swing.JButton();
        BasketbolcuB3 = new javax.swing.JButton();
        BasketbolcuB4 = new javax.swing.JButton();
        OrtayaK1 = new javax.swing.JButton();
        OrtayaK2 = new javax.swing.JButton();
        Başla = new javax.swing.JButton();
        PuanK = new javax.swing.JTextField();
        PuanB = new javax.swing.JTextField();
        SkorK = new javax.swing.JTextField();
        SkorB = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        SecilenPozisyon = new javax.swing.JButton();
        İsimKutusu = new javax.swing.JTextField();
        İsimLabeli = new javax.swing.JLabel();
        KullaniciLabeli = new javax.swing.JLabel();
        BilgisayarLabeli = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        KapatmaTuşu.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sİnan\\Desktop\\çarpı.jpeg")); // NOI18N
        KapatmaTuşu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KapatmaTuşuActionPerformed(evt);
            }
        });
        getContentPane().add(KapatmaTuşu);
        KapatmaTuşu.setBounds(1340, 20, 10, 10);

        FutbolcuB5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sİnan\\Desktop\\kartlar\\f.png")); // NOI18N
        getContentPane().add(FutbolcuB5);
        FutbolcuB5.setBounds(800, 330, 120, 200);

        FutbolcuB6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sİnan\\Desktop\\kartlar\\f.png")); // NOI18N
        getContentPane().add(FutbolcuB6);
        FutbolcuB6.setBounds(930, 330, 120, 200);

        FutbolcuB7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sİnan\\Desktop\\kartlar\\f.png")); // NOI18N
        getContentPane().add(FutbolcuB7);
        FutbolcuB7.setBounds(1060, 330, 120, 200);

        FutbolcuB8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sİnan\\Desktop\\kartlar\\f.png")); // NOI18N
        getContentPane().add(FutbolcuB8);
        FutbolcuB8.setBounds(1190, 330, 120, 200);

        BasketbolcuB5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sİnan\\Desktop\\kartlar\\b.png")); // NOI18N
        getContentPane().add(BasketbolcuB5);
        BasketbolcuB5.setBounds(800, 540, 120, 200);

        BasketbolcuB6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sİnan\\Desktop\\kartlar\\b.png")); // NOI18N
        getContentPane().add(BasketbolcuB6);
        BasketbolcuB6.setBounds(930, 540, 120, 200);

        BasketbolcuB7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sİnan\\Desktop\\kartlar\\b.png")); // NOI18N
        getContentPane().add(BasketbolcuB7);
        BasketbolcuB7.setBounds(1060, 540, 120, 200);

        BasketbolcuB8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sİnan\\Desktop\\kartlar\\b.png")); // NOI18N
        getContentPane().add(BasketbolcuB8);
        BasketbolcuB8.setBounds(1190, 540, 120, 200);

        FutbolcuK1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sİnan\\Desktop\\kartlar\\f.png")); // NOI18N
        FutbolcuK1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FutbolcuK1ActionPerformed(evt);
            }
        });
        getContentPane().add(FutbolcuK1);
        FutbolcuK1.setBounds(40, 330, 120, 200);

        FutbolcuK2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sİnan\\Desktop\\kartlar\\f.png")); // NOI18N
        FutbolcuK2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FutbolcuK2ActionPerformed(evt);
            }
        });
        getContentPane().add(FutbolcuK2);
        FutbolcuK2.setBounds(170, 330, 120, 200);

        FutbolcuK3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sİnan\\Desktop\\kartlar\\f.png")); // NOI18N
        FutbolcuK3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FutbolcuK3ActionPerformed(evt);
            }
        });
        getContentPane().add(FutbolcuK3);
        FutbolcuK3.setBounds(300, 330, 120, 200);

        FutbolcuK4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sİnan\\Desktop\\kartlar\\f.png")); // NOI18N
        FutbolcuK4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FutbolcuK4ActionPerformed(evt);
            }
        });
        getContentPane().add(FutbolcuK4);
        FutbolcuK4.setBounds(430, 330, 120, 200);

        FutbolcuB4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sİnan\\Desktop\\kartlar\\f.png")); // NOI18N
        getContentPane().add(FutbolcuB4);
        FutbolcuB4.setBounds(1190, 330, 120, 200);

        FutbolcuB3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sİnan\\Desktop\\kartlar\\f.png")); // NOI18N
        getContentPane().add(FutbolcuB3);
        FutbolcuB3.setBounds(1060, 330, 120, 200);

        FutbolcuB2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sİnan\\Desktop\\kartlar\\f.png")); // NOI18N
        getContentPane().add(FutbolcuB2);
        FutbolcuB2.setBounds(930, 330, 120, 200);

        FutbolcuB1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sİnan\\Desktop\\kartlar\\f.png")); // NOI18N
        getContentPane().add(FutbolcuB1);
        FutbolcuB1.setBounds(800, 330, 120, 200);

        BasketbolcuK1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sİnan\\Desktop\\kartlar\\b.png")); // NOI18N
        BasketbolcuK1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BasketbolcuK1ActionPerformed(evt);
            }
        });
        getContentPane().add(BasketbolcuK1);
        BasketbolcuK1.setBounds(40, 540, 120, 200);

        BasketbolcuK2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sİnan\\Desktop\\kartlar\\b.png")); // NOI18N
        BasketbolcuK2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BasketbolcuK2ActionPerformed(evt);
            }
        });
        getContentPane().add(BasketbolcuK2);
        BasketbolcuK2.setBounds(170, 540, 120, 200);

        BasketbolcuK3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sİnan\\Desktop\\kartlar\\b.png")); // NOI18N
        BasketbolcuK3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BasketbolcuK3ActionPerformed(evt);
            }
        });
        getContentPane().add(BasketbolcuK3);
        BasketbolcuK3.setBounds(300, 540, 120, 200);

        BasketbolcuK4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sİnan\\Desktop\\kartlar\\b.png")); // NOI18N
        BasketbolcuK4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BasketbolcuK4ActionPerformed(evt);
            }
        });
        getContentPane().add(BasketbolcuK4);
        BasketbolcuK4.setBounds(430, 540, 120, 200);

        BasketbolcuB1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sİnan\\Desktop\\kartlar\\b.png")); // NOI18N
        getContentPane().add(BasketbolcuB1);
        BasketbolcuB1.setBounds(800, 540, 120, 200);

        BasketbolcuB2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sİnan\\Desktop\\kartlar\\b.png")); // NOI18N
        getContentPane().add(BasketbolcuB2);
        BasketbolcuB2.setBounds(930, 540, 120, 200);

        BasketbolcuB3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sİnan\\Desktop\\kartlar\\b.png")); // NOI18N
        getContentPane().add(BasketbolcuB3);
        BasketbolcuB3.setBounds(1060, 540, 120, 200);

        BasketbolcuB4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sİnan\\Desktop\\kartlar\\b.png")); // NOI18N
        getContentPane().add(BasketbolcuB4);
        BasketbolcuB4.setBounds(1190, 540, 120, 200);
        getContentPane().add(OrtayaK1);
        OrtayaK1.setBounds(440, 110, 120, 200);

        OrtayaK2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrtayaK2ActionPerformed(evt);
            }
        });
        getContentPane().add(OrtayaK2);
        OrtayaK2.setBounds(790, 110, 120, 200);

        Başla.setBackground(new java.awt.Color(255, 0, 0));
        Başla.setText("BAŞLA");
        Başla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BaşlaActionPerformed(evt);
            }
        });
        getContentPane().add(Başla);
        Başla.setBounds(620, 240, 110, 50);

        PuanK.setEditable(false);
        PuanK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PuanKActionPerformed(evt);
            }
        });
        getContentPane().add(PuanK);
        PuanK.setBounds(230, 80, 90, 110);

        PuanB.setEditable(false);
        PuanB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PuanBActionPerformed(evt);
            }
        });
        getContentPane().add(PuanB);
        PuanB.setBounds(1080, 90, 90, 110);

        SkorK.setEditable(false);
        SkorK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SkorKActionPerformed(evt);
            }
        });
        getContentPane().add(SkorK);
        SkorK.setBounds(580, 130, 70, 70);

        SkorB.setEditable(false);
        SkorB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SkorBActionPerformed(evt);
            }
        });
        getContentPane().add(SkorB);
        SkorB.setBounds(699, 130, 70, 70);

        jTextField3.setEditable(false);
        jTextField3.setText("---------------");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(660, 150, 30, 22);

        SecilenPozisyon.setText("POZİSYON");
        SecilenPozisyon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SecilenPozisyonActionPerformed(evt);
            }
        });
        getContentPane().add(SecilenPozisyon);
        SecilenPozisyon.setBounds(569, 30, 200, 25);

        İsimKutusu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        İsimKutusu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                İsimKutusuActionPerformed(evt);
            }
        });
        getContentPane().add(İsimKutusu);
        İsimKutusu.setBounds(570, 480, 190, 22);

        İsimLabeli.setForeground(new java.awt.Color(255, 0, 0));
        İsimLabeli.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        İsimLabeli.setText("İSİM GİRİNİZ");
        getContentPane().add(İsimLabeli);
        İsimLabeli.setBounds(610, 460, 100, 16);

        KullaniciLabeli.setForeground(new java.awt.Color(0, 0, 153));
        KullaniciLabeli.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        KullaniciLabeli.setText("  ");
        getContentPane().add(KullaniciLabeli);
        KullaniciLabeli.setBounds(190, 50, 160, 16);

        BilgisayarLabeli.setForeground(new java.awt.Color(204, 204, 0));
        BilgisayarLabeli.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BilgisayarLabeli.setText("BİLGİSAYAR");
        getContentPane().add(BilgisayarLabeli);
        BilgisayarLabeli.setBounds(1060, 50, 130, 16);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sİnan\\Desktop\\collage.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1370, 770);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1370, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1370, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KapatmaTuşuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KapatmaTuşuActionPerformed
        // TODO add your handling code here:
        int sonuc = JOptionPane.showConfirmDialog(null,
                "Kapatmak İstediğinize Emin Misiniz?",
                "Uyarı",
                JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (sonuc == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_KapatmaTuşuActionPerformed

    private void BaşlaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BaşlaActionPerformed
        // TODO add your handling code here:
       Başla.setVisible(false);
       ArrayList<String> yenilist = new ArrayList<String>();
       yenilist.add(ad1);
       yenilist.add(ad2);
       yenilist.add(ad3);
       yenilist.add(ad4);
       yenilist.add(ad5);
       yenilist.add(ad6);
       yenilist.add(ad7);
       yenilist.add(ad8);
       Collections.shuffle(yenilist);
       Oyuncu.a1=(yenilist.get(0));
       Oyuncu.a2=(yenilist.get(1));
       Oyuncu.a3=(yenilist.get(2));
       Oyuncu.a4=(yenilist.get(3));
       Oyuncu.a5=(yenilist.get(4));
       Oyuncu.a6=(yenilist.get(5));
       Oyuncu.a7=(yenilist.get(6));
       Oyuncu.a8=(yenilist.get(7));
       
       
       ArrayList<String> yenilist2 = new ArrayList<String>();
       yenilist2.add(bd1);
       yenilist2.add(bd2);
       yenilist2.add(bd3);
       yenilist2.add(bd4);
       yenilist2.add(bd5);
       yenilist2.add(bd6);
       yenilist2.add(bd7);
       yenilist2.add(bd8);
       Collections.shuffle(yenilist2);
       Oyuncu.b1=(yenilist2.get(0));
       Oyuncu.b2=(yenilist2.get(1));
       Oyuncu.b3=(yenilist2.get(2));
       Oyuncu.b4=(yenilist2.get(3));
       Oyuncu.b5=(yenilist2.get(4));
       Oyuncu.b6=(yenilist2.get(5));
       Oyuncu.b7=(yenilist2.get(6));
       Oyuncu.b8=(yenilist2.get(7));
       
       System.out.println(İsimKutusu.getText()+": ");
       for(int j=0;j<=3;j++){
           System.out.println(yenilist.get(j));     
           System.out.println(yenilist2.get(j));
            } 
       
           BasketbolcuK1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/" + yenilist2.get(0) + ".png")));
           BasketbolcuK2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/" + yenilist2.get(1) + ".png")));
           BasketbolcuK3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/" + yenilist2.get(2) + ".png")));
           BasketbolcuK4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/" + yenilist2.get(3) + ".png")));
          
           
           BasketbolcuB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/" + yenilist2.get(4) + ".png")));
           BasketbolcuB2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/" + yenilist2.get(5) + ".png")));
           BasketbolcuB3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/" + yenilist2.get(6) + ".png")));
           BasketbolcuB4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/" + yenilist2.get(7) + ".png")));
           
           
       System.out.println("");
       System.out.println("Bilgisayar: ");
       for(int j=4;j<=7;j++){
           System.out.println(yenilist.get(j));     
           System.out.println(yenilist2.get(j));
            } 
       
           FutbolcuK1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/" + yenilist.get(0) + ".png")));
           FutbolcuK2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/" + yenilist.get(1) + ".png")));
           FutbolcuK3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/" + yenilist.get(2) + ".png")));
           FutbolcuK4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/" + yenilist.get(3) + ".png")));
           
           FutbolcuB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/" + yenilist.get(4) + ".png")));
           FutbolcuB2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/" + yenilist.get(5) + ".png")));
           FutbolcuB3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/" + yenilist.get(6) + ".png")));
           FutbolcuB4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/" + yenilist.get(7) + ".png")));
         
       BasketbolcuK1.setEnabled(false);
        BasketbolcuK2.setEnabled(false);
        BasketbolcuK3.setEnabled(false);
        BasketbolcuK4.setEnabled(false);
        
        FutbolcuK1.setEnabled(true);
        FutbolcuK2.setEnabled(true);
        FutbolcuK3.setEnabled(true);
        FutbolcuK4.setEnabled(true);
        FutbolcuB1.setEnabled(true);
        FutbolcuB2.setEnabled(true);
        FutbolcuB3.setEnabled(true);
        FutbolcuB4.setEnabled(true);
        FutbolcuB5.setEnabled(true);
        FutbolcuB6.setEnabled(true);
        FutbolcuB7.setEnabled(true);
        FutbolcuB8.setEnabled(true);
        BasketbolcuB1.setEnabled(true);
        BasketbolcuB2.setEnabled(true);
        BasketbolcuB3.setEnabled(true);
        BasketbolcuB4.setEnabled(true);
        BasketbolcuB5.setEnabled(true);
        BasketbolcuB6.setEnabled(true);
        BasketbolcuB7.setEnabled(true);
        BasketbolcuB8.setEnabled(true);
        
        Kullanici.KullaniciIsim = İsimKutusu.getText();
        Kullanici.KullaniciSkor = puan1;
        Bilgisayar.BilgisayarSkor = puan2;
        
    }//GEN-LAST:event_BaşlaActionPerformed

    private void FutbolcuK1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FutbolcuK1ActionPerformed
        // TODO add your handling code here:
        if(sayi%2==0){
            FutbolcuK1.setEnabled(false);
            FutbolcuK2.setEnabled(false);
            FutbolcuK3.setEnabled(false);
            FutbolcuK4.setEnabled(false);
            BasketbolcuK1.setEnabled(true);
            BasketbolcuK2.setEnabled(true);
            BasketbolcuK3.setEnabled(true);
            BasketbolcuK4.setEnabled(true);
        }
        else{
            FutbolcuK1.setEnabled(true);
            FutbolcuK2.setEnabled(true);
            FutbolcuK3.setEnabled(true);
            FutbolcuK4.setEnabled(true);
            BasketbolcuK1.setEnabled(false);
            BasketbolcuK2.setEnabled(false);
            BasketbolcuK3.setEnabled(false);
            BasketbolcuK4.setEnabled(false);
        }
        sayi++;
        tik++;
        SecilenPozisyon.setText(Test.PozisyonBilgisi("futbol"));
        OrtayaK1.setIcon(FutbolcuK1.getIcon());
        FutbolcuK1.setVisible(false);
        OrtayaK1.setVisible(true);
        SkorK.setText(Integer.toString(Oyuncu.SkorGoster("futbol",0,SecilenPozisyon.getText())));
        if (r1=="1") {
            OrtayaK2.setIcon(FutbolcuB1.getIcon());
            OrtayaK2.setVisible(true);
            FutbolcuB1.setVisible(false);
            FutbolcuB5.setVisible(false);
            SkorB.setText(Integer.toString(Oyuncu.SkorGoster("futbol",4,SecilenPozisyon.getText())));
        }
        else if (r1=="2") {
            OrtayaK2.setIcon(FutbolcuB2.getIcon());
            OrtayaK2.setVisible(true);
            FutbolcuB2.setVisible(false);
            FutbolcuB6.setVisible(false);
            SkorB.setText(Integer.toString(Oyuncu.SkorGoster("futbol",5,SecilenPozisyon.getText())));
        }
        else if (r1=="3") {
            OrtayaK2.setIcon(FutbolcuB3.getIcon());
            OrtayaK2.setVisible(true);
            FutbolcuB3.setVisible(false);
            FutbolcuB7.setVisible(false);
            SkorB.setText(Integer.toString(Oyuncu.SkorGoster("futbol",6,SecilenPozisyon.getText())));
        }
        else if (r1=="4") {
            OrtayaK2.setIcon(FutbolcuB4.getIcon());
            OrtayaK2.setVisible(true);
            FutbolcuB4.setVisible(false);
            FutbolcuB8.setVisible(false);
            SkorB.setText(Integer.toString(Oyuncu.SkorGoster("futbol",7,SecilenPozisyon.getText())));
        }
        if(Integer.valueOf(SkorK.getText())<Integer.valueOf(SkorB.getText())){
            puan2=puan2+10;
        }  
        else if(Integer.valueOf(SkorK.getText())>Integer.valueOf(SkorB.getText())){
            puan1=puan1+10;
        }
        PuanK.setText(Integer.toString(puan1));
        PuanB.setText(Integer.toString(puan2));
        if(tik==8 && puan1<puan2)
        {
            JOptionPane.showMessageDialog(null,KullaniciLabeli.getText()+" Skor: "+Integer.toString(puan1)+"\n"+"Bilgisayar Skor: "+Integer.toString(puan2), "Bilgisayar Kazandı!" , JOptionPane.INFORMATION_MESSAGE);
        }
        else if(tik==8 && puan1>puan2)
        {
            JOptionPane.showMessageDialog(null,KullaniciLabeli.getText()+" Skor: "+Integer.toString(puan1)+"\n"+"Bilgisayar Skor: "+Integer.toString(puan2),KullaniciLabeli.getText()+" Kazandı!" , JOptionPane.INFORMATION_MESSAGE);
            
        }
        else if(tik==8 && puan1==puan2)
        {
            JOptionPane.showMessageDialog(null,KullaniciLabeli.getText()+" Skor: "+Integer.toString(puan1)+"\n"+"Bilgisayar Skor: "+Integer.toString(puan2),"Oyun Berabere Sonuçlandı!" , JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_FutbolcuK1ActionPerformed

    private void BasketbolcuK2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BasketbolcuK2ActionPerformed
       
        if(sayi%2==1){
            BasketbolcuK1.setEnabled(false);
            BasketbolcuK2.setEnabled(false);
            BasketbolcuK3.setEnabled(false);
            BasketbolcuK4.setEnabled(false);
            FutbolcuK1.setEnabled(true);
            FutbolcuK2.setEnabled(true);
            FutbolcuK3.setEnabled(true);
            FutbolcuK4.setEnabled(true);
        }
        else{
            BasketbolcuK1.setEnabled(true);
            BasketbolcuK2.setEnabled(true);
            BasketbolcuK3.setEnabled(true);
            BasketbolcuK4.setEnabled(true);
            FutbolcuK1.setEnabled(false);
            FutbolcuK2.setEnabled(false);
            FutbolcuK3.setEnabled(false);
            FutbolcuK4.setEnabled(false);
        }
        sayi++;
        tik++;
        SecilenPozisyon.setText(Test.PozisyonBilgisi("basketbol"));
        OrtayaK1.setIcon(BasketbolcuK2.getIcon());
        BasketbolcuK2.setVisible(false);
        OrtayaK1.setVisible(true); 
        SkorK.setText(Integer.toString(Oyuncu.SkorGoster("basketbol",1,SecilenPozisyon.getText())));
        if (R2=="1") {
            OrtayaK2.setIcon(BasketbolcuB1.getIcon());
            OrtayaK2.setVisible(true);
            BasketbolcuB1.setVisible(false);
            BasketbolcuB5.setVisible(false);
            SkorB.setText(Integer.toString(Oyuncu.SkorGoster("basketbol",4,SecilenPozisyon.getText())));
        }
        else if (R2=="2") {
            OrtayaK2.setIcon(BasketbolcuB2.getIcon());
            OrtayaK2.setVisible(true);
            BasketbolcuB2.setVisible(false);
            BasketbolcuB6.setVisible(false);
            SkorB.setText(Integer.toString(Oyuncu.SkorGoster("basketbol",5,SecilenPozisyon.getText())));
        }
        else if (R2=="3") {
            OrtayaK2.setIcon(BasketbolcuB3.getIcon());
            OrtayaK2.setVisible(true);
            BasketbolcuB3.setVisible(false);
            BasketbolcuB7.setVisible(false);
            SkorB.setText(Integer.toString(Oyuncu.SkorGoster("basketbol",6,SecilenPozisyon.getText())));
        }
        else if (R2=="4") {
            OrtayaK2.setIcon(BasketbolcuB4.getIcon());
            OrtayaK2.setVisible(true);
            BasketbolcuB4.setVisible(false);
            BasketbolcuB8.setVisible(false);
            SkorB.setText(Integer.toString(Oyuncu.SkorGoster("basketbol",7,SecilenPozisyon.getText())));
        }
        if(Integer.valueOf(SkorK.getText())<Integer.valueOf(SkorB.getText())){
            puan2=puan2+10;
        }  
        else if(Integer.valueOf(SkorK.getText())>Integer.valueOf(SkorB.getText())){
            puan1=puan1+10;
        }
        PuanK.setText(Integer.toString(puan1));
        PuanB.setText(Integer.toString(puan2));
      if(tik==8 && puan1<puan2)
        {
            JOptionPane.showMessageDialog(null,KullaniciLabeli.getText()+" Skor: "+Integer.toString(puan1)+"\n"+"Bilgisayar Skor: "+Integer.toString(puan2), "Bilgisayar Kazandı!" , JOptionPane.INFORMATION_MESSAGE);
        }
        else if(tik==8 && puan1>puan2)
        {
            JOptionPane.showMessageDialog(null,KullaniciLabeli.getText()+" Skor: "+Integer.toString(puan1)+"\n"+"Bilgisayar Skor: "+Integer.toString(puan2),KullaniciLabeli.getText()+" Kazandı!" , JOptionPane.INFORMATION_MESSAGE);
            
        }
        else if(tik==8 && puan1==puan2)
        {
            JOptionPane.showMessageDialog(null,KullaniciLabeli.getText()+" Skor: "+Integer.toString(puan1)+"\n"+"Bilgisayar Skor: "+Integer.toString(puan2),"Oyun Berabere Sonuçlandı!" , JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_BasketbolcuK2ActionPerformed

    private void FutbolcuK2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FutbolcuK2ActionPerformed
        // TODO add your handling code here:
        if(sayi%2==0){
            FutbolcuK1.setEnabled(false);
            FutbolcuK2.setEnabled(false);
            FutbolcuK3.setEnabled(false);
            FutbolcuK4.setEnabled(false);
            BasketbolcuK1.setEnabled(true);
            BasketbolcuK2.setEnabled(true);
            BasketbolcuK3.setEnabled(true);
            BasketbolcuK4.setEnabled(true);
        }
        else{
            FutbolcuK1.setEnabled(true);
            FutbolcuK2.setEnabled(true);
            FutbolcuK3.setEnabled(true);
            FutbolcuK4.setEnabled(true);
            BasketbolcuK1.setEnabled(false);
            BasketbolcuK2.setEnabled(false);
            BasketbolcuK3.setEnabled(false);
            BasketbolcuK4.setEnabled(false);
        }
        sayi++;
        tik++;
        SecilenPozisyon.setText(Test.PozisyonBilgisi("futbol"));
        OrtayaK1.setIcon(FutbolcuK2.getIcon());
        FutbolcuK2.setVisible(false);
        OrtayaK1.setVisible(true);
        
        SkorK.setText(Integer.toString(Oyuncu.SkorGoster("futbol",1,SecilenPozisyon.getText())));
        if (r2=="1") {
            OrtayaK2.setIcon(FutbolcuB1.getIcon());
            OrtayaK2.setVisible(true);
            FutbolcuB1.setVisible(false);
            FutbolcuB5.setVisible(false);
            SkorB.setText(Integer.toString(Oyuncu.SkorGoster("futbol",4,SecilenPozisyon.getText())));
        }
        else if (r2=="2") {
            OrtayaK2.setIcon(FutbolcuB2.getIcon());
            OrtayaK2.setVisible(true);
            FutbolcuB2.setVisible(false);
            FutbolcuB6.setVisible(false);
            SkorB.setText(Integer.toString(Oyuncu.SkorGoster("futbol",5,SecilenPozisyon.getText())));
        }
        else if (r2=="3") {
            OrtayaK2.setIcon(FutbolcuB3.getIcon());
            OrtayaK2.setVisible(true);
            FutbolcuB3.setVisible(false);
            FutbolcuB7.setVisible(false);
            SkorB.setText(Integer.toString(Oyuncu.SkorGoster("futbol",6,SecilenPozisyon.getText())));
        }
        else if (r2=="4") {
            OrtayaK2.setIcon(FutbolcuB4.getIcon());
            OrtayaK2.setVisible(true);
            FutbolcuB4.setVisible(false);
            FutbolcuB8.setVisible(false);
            SkorB.setText(Integer.toString(Oyuncu.SkorGoster("futbol",7,SecilenPozisyon.getText())));
        }
        if(Integer.valueOf(SkorK.getText())<Integer.valueOf(SkorB.getText())){
            puan2=puan2+10;
        }  
        else if(Integer.valueOf(SkorK.getText())>Integer.valueOf(SkorB.getText())){
            puan1=puan1+10;
        }
        PuanK.setText(Integer.toString(puan1));
        PuanB.setText(Integer.toString(puan2));
        if(tik==8 && puan1<puan2)
        {
            JOptionPane.showMessageDialog(null,KullaniciLabeli.getText()+" Skor: "+Integer.toString(puan1)+"\n"+"Bilgisayar Skor: "+Integer.toString(puan2), "Bilgisayar Kazandı!" , JOptionPane.INFORMATION_MESSAGE);
        }
        else if(tik==8 && puan1>puan2)
        {
            JOptionPane.showMessageDialog(null,KullaniciLabeli.getText()+" Skor: "+Integer.toString(puan1)+"\n"+"Bilgisayar Skor: "+Integer.toString(puan2),KullaniciLabeli.getText()+" Kazandı!" , JOptionPane.INFORMATION_MESSAGE);
            
        }
        else if(tik==8 && puan1==puan2)
        {
            JOptionPane.showMessageDialog(null,KullaniciLabeli.getText()+" Skor: "+Integer.toString(puan1)+"\n"+"Bilgisayar Skor: "+Integer.toString(puan2),"Oyun Berabere Sonuçlandı!" , JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_FutbolcuK2ActionPerformed

    private void FutbolcuK3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FutbolcuK3ActionPerformed
        // TODO add your handling code here:
        if(sayi%2==0){
            FutbolcuK1.setEnabled(false);
            FutbolcuK2.setEnabled(false);
            FutbolcuK3.setEnabled(false);
            FutbolcuK4.setEnabled(false);
            BasketbolcuK1.setEnabled(true);
            BasketbolcuK2.setEnabled(true);
            BasketbolcuK3.setEnabled(true);
            BasketbolcuK4.setEnabled(true);
        }
        else{
            FutbolcuK1.setEnabled(true);
            FutbolcuK2.setEnabled(true);
            FutbolcuK3.setEnabled(true);
            FutbolcuK4.setEnabled(true);
            BasketbolcuK1.setEnabled(false);
            BasketbolcuK2.setEnabled(false);
            BasketbolcuK3.setEnabled(false);
            BasketbolcuK4.setEnabled(false);
        }
        sayi++;
        tik++;
        SecilenPozisyon.setText(Test.PozisyonBilgisi("futbol"));
        OrtayaK1.setIcon(FutbolcuK3.getIcon());
        FutbolcuK3.setVisible(false);
        OrtayaK1.setVisible(true);
        SkorK.setText(Integer.toString(Oyuncu.SkorGoster("futbol",2,SecilenPozisyon.getText())));
        if (r3=="1") {
            OrtayaK2.setIcon(FutbolcuB1.getIcon());
            OrtayaK2.setVisible(true);
            FutbolcuB1.setVisible(false);
            FutbolcuB5.setVisible(false);
            SkorB.setText(Integer.toString(Oyuncu.SkorGoster("futbol",4,SecilenPozisyon.getText())));
        }
        else if (r3=="2") {
            OrtayaK2.setIcon(FutbolcuB2.getIcon());
            OrtayaK2.setVisible(true);
            FutbolcuB2.setVisible(false);
            FutbolcuB6.setVisible(false);
            SkorB.setText(Integer.toString(Oyuncu.SkorGoster("futbol",5,SecilenPozisyon.getText())));
        }
        else if (r3=="3") {
            OrtayaK2.setIcon(FutbolcuB3.getIcon());
            OrtayaK2.setVisible(true);
            FutbolcuB3.setVisible(false);
            FutbolcuB7.setVisible(false);
            SkorB.setText(Integer.toString(Oyuncu.SkorGoster("futbol",6,SecilenPozisyon.getText())));
        }
        else if (r3=="4") {
            OrtayaK2.setIcon(FutbolcuB4.getIcon());
            OrtayaK2.setVisible(true);
            FutbolcuB4.setVisible(false);
            FutbolcuB8.setVisible(false);
            SkorB.setText(Integer.toString(Oyuncu.SkorGoster("futbol",7,SecilenPozisyon.getText())));
        }
        if(Integer.valueOf(SkorK.getText())<Integer.valueOf(SkorB.getText())){
            puan2=puan2+10;
        }  
        else if(Integer.valueOf(SkorK.getText())>Integer.valueOf(SkorB.getText())){
            puan1=puan1+10;
        }
        PuanK.setText(Integer.toString(puan1));
        PuanB.setText(Integer.toString(puan2));
        if(tik==8 && puan1<puan2)
        {
            JOptionPane.showMessageDialog(null,KullaniciLabeli.getText()+" Skor: "+Integer.toString(puan1)+"\n"+"Bilgisayar Skor: "+Integer.toString(puan2), "Bilgisayar Kazandı!" , JOptionPane.INFORMATION_MESSAGE);
        }
        else if(tik==8 && puan1>puan2)
        {
            JOptionPane.showMessageDialog(null,KullaniciLabeli.getText()+" Skor: "+Integer.toString(puan1)+"\n"+"Bilgisayar Skor: "+Integer.toString(puan2),KullaniciLabeli.getText()+" Kazandı!" , JOptionPane.INFORMATION_MESSAGE);
            
        }
        else if(tik==8 && puan1==puan2)
        {
            JOptionPane.showMessageDialog(null,KullaniciLabeli.getText()+" Skor: "+Integer.toString(puan1)+"\n"+"Bilgisayar Skor: "+Integer.toString(puan2),"Oyun Berabere Sonuçlandı!" , JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_FutbolcuK3ActionPerformed

    private void FutbolcuK4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FutbolcuK4ActionPerformed
        // TODO add your handling code here:
        if(sayi%2==0){
            FutbolcuK1.setEnabled(false);
            FutbolcuK2.setEnabled(false);
            FutbolcuK3.setEnabled(false);
            FutbolcuK4.setEnabled(false);
            BasketbolcuK1.setEnabled(true);
            BasketbolcuK2.setEnabled(true);
            BasketbolcuK3.setEnabled(true);
            BasketbolcuK4.setEnabled(true);
        }
        else{
            FutbolcuK1.setEnabled(true);
            FutbolcuK2.setEnabled(true);
            FutbolcuK3.setEnabled(true);
            FutbolcuK4.setEnabled(true);
            BasketbolcuK1.setEnabled(false);
            BasketbolcuK2.setEnabled(false);
            BasketbolcuK3.setEnabled(false);
            BasketbolcuK4.setEnabled(false);
        }
        sayi++;
        tik++;
        SecilenPozisyon.setText(Test.PozisyonBilgisi("futbol"));
        OrtayaK1.setIcon(FutbolcuK4.getIcon());
        FutbolcuK4.setVisible(false);
        OrtayaK1.setVisible(true);
        SkorK.setText(Integer.toString(Oyuncu.SkorGoster("futbol",3,SecilenPozisyon.getText())));
        if (r4=="1") {
            OrtayaK2.setIcon(FutbolcuB1.getIcon());
            OrtayaK2.setVisible(true);
            FutbolcuB1.setVisible(false);
            FutbolcuB5.setVisible(false);
            SkorB.setText(Integer.toString(Oyuncu.SkorGoster("futbol",4,SecilenPozisyon.getText())));
        }
        else if (r4=="2") {
            OrtayaK2.setIcon(FutbolcuB2.getIcon());
            OrtayaK2.setVisible(true);
            FutbolcuB2.setVisible(false);
            FutbolcuB6.setVisible(false);
            SkorB.setText(Integer.toString(Oyuncu.SkorGoster("futbol",5,SecilenPozisyon.getText())));
        }
        else if (r4=="3") {
            OrtayaK2.setIcon(FutbolcuB3.getIcon());
            OrtayaK2.setVisible(true);
            FutbolcuB3.setVisible(false);
            FutbolcuB7.setVisible(false);
            SkorB.setText(Integer.toString(Oyuncu.SkorGoster("futbol",6,SecilenPozisyon.getText())));
        }
        else if (r4=="4") {
            OrtayaK2.setIcon(FutbolcuB4.getIcon());
            OrtayaK2.setVisible(true);
            FutbolcuB4.setVisible(false);
            FutbolcuB8.setVisible(false);
            SkorB.setText(Integer.toString(Oyuncu.SkorGoster("futbol",7,SecilenPozisyon.getText())));
        }
        if(Integer.valueOf(SkorK.getText())<Integer.valueOf(SkorB.getText())){
            puan2=puan2+10;
        }  
        else if(Integer.valueOf(SkorK.getText())>Integer.valueOf(SkorB.getText())){
            puan1=puan1+10;
        }
        PuanK.setText(Integer.toString(puan1));
        PuanB.setText(Integer.toString(puan2));
        if(tik==8 && puan1<puan2)
        {
            JOptionPane.showMessageDialog(null,KullaniciLabeli.getText()+" Skor: "+Integer.toString(puan1)+"\n"+"Bilgisayar Skor: "+Integer.toString(puan2), "Bilgisayar Kazandı!" , JOptionPane.INFORMATION_MESSAGE);
        }
        else if(tik==8 && puan1>puan2)
        {
            JOptionPane.showMessageDialog(null,KullaniciLabeli.getText()+" Skor: "+Integer.toString(puan1)+"\n"+"Bilgisayar Skor: "+Integer.toString(puan2),KullaniciLabeli.getText()+" Kazandı!" , JOptionPane.INFORMATION_MESSAGE);
            
        }
        else if(tik==8 && puan1==puan2)
        {
            JOptionPane.showMessageDialog(null,KullaniciLabeli.getText()+" Skor: "+Integer.toString(puan1)+"\n"+"Bilgisayar Skor: "+Integer.toString(puan2),"Oyun Berabere Sonuçlandı!" , JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_FutbolcuK4ActionPerformed

    private void BasketbolcuK1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BasketbolcuK1ActionPerformed
       if(sayi%2==1){
            BasketbolcuK1.setEnabled(false);
            BasketbolcuK2.setEnabled(false);
            BasketbolcuK3.setEnabled(false);
            BasketbolcuK4.setEnabled(false);
            FutbolcuK1.setEnabled(true);
            FutbolcuK2.setEnabled(true);
            FutbolcuK3.setEnabled(true);
            FutbolcuK4.setEnabled(true);
        }
        else{
            BasketbolcuK1.setEnabled(true);
            BasketbolcuK2.setEnabled(true);
            BasketbolcuK3.setEnabled(true);
            BasketbolcuK4.setEnabled(true);
            FutbolcuK1.setEnabled(false);
            FutbolcuK2.setEnabled(false);
            FutbolcuK3.setEnabled(false);
            FutbolcuK4.setEnabled(false);
        }
        sayi++;
        tik++;
        SecilenPozisyon.setText(Test.PozisyonBilgisi("basketbol"));
        OrtayaK1.setIcon(BasketbolcuK1.getIcon());
        BasketbolcuK1.setVisible(false);
        OrtayaK1.setVisible(true);
        SkorK.setText(Integer.toString(Oyuncu.SkorGoster("basketbol",0,SecilenPozisyon.getText())));
        if (R1=="1") {
            OrtayaK2.setIcon(BasketbolcuB1.getIcon());
            OrtayaK2.setVisible(true);
            BasketbolcuB1.setVisible(false);
            BasketbolcuB5.setVisible(false);
            SkorB.setText(Integer.toString(Oyuncu.SkorGoster("basketbol",4,SecilenPozisyon.getText())));
        }
        else if (R1=="2") {
            OrtayaK2.setIcon(BasketbolcuB2.getIcon());
            OrtayaK2.setVisible(true);
            BasketbolcuB2.setVisible(false);
            BasketbolcuB6.setVisible(false);
            SkorB.setText(Integer.toString(Oyuncu.SkorGoster("basketbol",5,SecilenPozisyon.getText())));
        }
        else if (R1=="3") {
            OrtayaK2.setIcon(BasketbolcuB3.getIcon());
            OrtayaK2.setVisible(true);
            BasketbolcuB3.setVisible(false);
            BasketbolcuB7.setVisible(false);
            SkorB.setText(Integer.toString(Oyuncu.SkorGoster("basketbol",6,SecilenPozisyon.getText())));
        }
        else if (R1=="4") {
            OrtayaK2.setIcon(BasketbolcuB4.getIcon());
            OrtayaK2.setVisible(true);
            BasketbolcuB4.setVisible(false);
            BasketbolcuB8.setVisible(false);
            SkorB.setText(Integer.toString(Oyuncu.SkorGoster("basketbol",7,SecilenPozisyon.getText())));
        }
        if(Integer.valueOf(SkorK.getText())<Integer.valueOf(SkorB.getText())){
            puan2=puan2+10;
        }  
        else if(Integer.valueOf(SkorK.getText())>Integer.valueOf(SkorB.getText())){
            puan1=puan1+10;
        }
        
        PuanK.setText(Integer.toString(puan1));
        PuanB.setText(Integer.toString(puan2));
        if(tik==8 && puan1<puan2)
        {
            JOptionPane.showMessageDialog(null,KullaniciLabeli.getText()+" Skor: "+Integer.toString(puan1)+"\n"+"Bilgisayar Skor: "+Integer.toString(puan2), "Bilgisayar Kazandı!" , JOptionPane.INFORMATION_MESSAGE);
        }
        else if(tik==8 && puan1>puan2)
        {
            JOptionPane.showMessageDialog(null,KullaniciLabeli.getText()+" Skor: "+Integer.toString(puan1)+"\n"+"Bilgisayar Skor: "+Integer.toString(puan2),KullaniciLabeli.getText()+" Kazandı!" , JOptionPane.INFORMATION_MESSAGE);
            
        }
        else if(tik==8 && puan1==puan2)
        {
            JOptionPane.showMessageDialog(null,KullaniciLabeli.getText()+" Skor: "+Integer.toString(puan1)+"\n"+"Bilgisayar Skor: "+Integer.toString(puan2),"Oyun Berabere Sonuçlandı!" , JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_BasketbolcuK1ActionPerformed

    private void BasketbolcuK3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BasketbolcuK3ActionPerformed
        if(sayi%2==1){
            BasketbolcuK1.setEnabled(false);
            BasketbolcuK2.setEnabled(false);
            BasketbolcuK3.setEnabled(false);
            BasketbolcuK4.setEnabled(false);
            FutbolcuK1.setEnabled(true);
            FutbolcuK2.setEnabled(true);
            FutbolcuK3.setEnabled(true);
            FutbolcuK4.setEnabled(true);
        }
        else{
            BasketbolcuK1.setEnabled(true);
            BasketbolcuK2.setEnabled(true);
            BasketbolcuK3.setEnabled(true);
            BasketbolcuK4.setEnabled(true);
            FutbolcuK1.setEnabled(false);
            FutbolcuK2.setEnabled(false);
            FutbolcuK3.setEnabled(false);
            FutbolcuK4.setEnabled(false);
        }
        sayi++;
        tik++;
        SecilenPozisyon.setText(Test.PozisyonBilgisi("basketbol"));
        OrtayaK1.setIcon(BasketbolcuK3.getIcon());
        BasketbolcuK3.setVisible(false);
        OrtayaK1.setVisible(true);
        SkorK.setText(Integer.toString(Oyuncu.SkorGoster("basketbol",2,SecilenPozisyon.getText())));
        if (R3=="1") {
            OrtayaK2.setIcon(BasketbolcuB1.getIcon());
            OrtayaK2.setVisible(true);
            BasketbolcuB1.setVisible(false);
            BasketbolcuB5.setVisible(false);
            SkorB.setText(Integer.toString(Oyuncu.SkorGoster("basketbol",4,SecilenPozisyon.getText())));
        }
        else if (R3=="2") {
            OrtayaK2.setIcon(BasketbolcuB2.getIcon());
            OrtayaK2.setVisible(true);
            BasketbolcuB2.setVisible(false);
            BasketbolcuB6.setVisible(false);
            SkorB.setText(Integer.toString(Oyuncu.SkorGoster("basketbol",5,SecilenPozisyon.getText())));
        }
        else if (R3=="3") {
            OrtayaK2.setIcon(BasketbolcuB3.getIcon());
            OrtayaK2.setVisible(true);
            BasketbolcuB3.setVisible(false);
            BasketbolcuB7.setVisible(false);
            SkorB.setText(Integer.toString(Oyuncu.SkorGoster("basketbol",6,SecilenPozisyon.getText())));
        }
        else if (R3=="4") {
            OrtayaK2.setIcon(BasketbolcuB4.getIcon());
            OrtayaK2.setVisible(true);
            BasketbolcuB4.setVisible(false);
            BasketbolcuB8.setVisible(false);
            SkorB.setText(Integer.toString(Oyuncu.SkorGoster("basketbol",7,SecilenPozisyon.getText())));
        }
        if(Integer.valueOf(SkorK.getText())<Integer.valueOf(SkorB.getText())){
            puan2=puan2+10;
        }  
        else if(Integer.valueOf(SkorK.getText())>Integer.valueOf(SkorB.getText())){
            puan1=puan1+10;
        }
        PuanK.setText(Integer.toString(puan1));
        PuanB.setText(Integer.toString(puan2));
        if(tik==8 && puan1<puan2)
        {
            JOptionPane.showMessageDialog(null,KullaniciLabeli.getText()+" Skor: "+Integer.toString(puan1)+"\n"+"Bilgisayar Skor: "+Integer.toString(puan2), "Bilgisayar Kazandı!" , JOptionPane.INFORMATION_MESSAGE);
        }
        else if(tik==8 && puan1>puan2)
        {
            JOptionPane.showMessageDialog(null,KullaniciLabeli.getText()+" Skor: "+Integer.toString(puan1)+"\n"+"Bilgisayar Skor: "+Integer.toString(puan2),KullaniciLabeli.getText()+" Kazandı!" , JOptionPane.INFORMATION_MESSAGE);
            
        }
        else if(tik==8 && puan1==puan2)
        {
            JOptionPane.showMessageDialog(null,KullaniciLabeli.getText()+" Skor: "+Integer.toString(puan1)+"\n"+"Bilgisayar Skor: "+Integer.toString(puan2),"Oyun Berabere Sonuçlandı!" , JOptionPane.INFORMATION_MESSAGE);
        }
           
    }//GEN-LAST:event_BasketbolcuK3ActionPerformed

    private void BasketbolcuK4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BasketbolcuK4ActionPerformed
        if(sayi%2==1){
            BasketbolcuK1.setEnabled(false);
            BasketbolcuK2.setEnabled(false);
            BasketbolcuK3.setEnabled(false);
            BasketbolcuK4.setEnabled(false);
            FutbolcuK1.setEnabled(true);
            FutbolcuK2.setEnabled(true);
            FutbolcuK3.setEnabled(true);
            FutbolcuK4.setEnabled(true);
        }
        else{
            BasketbolcuK1.setEnabled(true);
            BasketbolcuK2.setEnabled(true);
            BasketbolcuK3.setEnabled(true);
            BasketbolcuK4.setEnabled(true);
            FutbolcuK1.setEnabled(false);
            FutbolcuK2.setEnabled(false);
            FutbolcuK3.setEnabled(false);
            FutbolcuK4.setEnabled(false);
        }
        
        sayi++;
        tik++;
        SecilenPozisyon.setText(Test.PozisyonBilgisi("basketbol"));
        OrtayaK1.setIcon(BasketbolcuK4.getIcon());
        BasketbolcuK4.setVisible(false);
        OrtayaK1.setVisible(true);
        SkorK.setText(Integer.toString(Oyuncu.SkorGoster("basketbol",3,SecilenPozisyon.getText())));
        if (R4=="1") {
            OrtayaK2.setIcon(BasketbolcuB1.getIcon());
            OrtayaK2.setVisible(true);
            BasketbolcuB1.setVisible(false);
            BasketbolcuB5.setVisible(false);
            SkorB.setText(Integer.toString(Oyuncu.SkorGoster("basketbol",4,SecilenPozisyon.getText())));
        }
        else if (R4=="2") {
            OrtayaK2.setIcon(BasketbolcuB2.getIcon());
            OrtayaK2.setVisible(true);
            BasketbolcuB2.setVisible(false);
            BasketbolcuB6.setVisible(false);
            SkorB.setText(Integer.toString(Oyuncu.SkorGoster("basketbol",5,SecilenPozisyon.getText())));
        }
        else if (R4=="3") {
            OrtayaK2.setIcon(BasketbolcuB3.getIcon());
            OrtayaK2.setVisible(true);
            BasketbolcuB3.setVisible(false);
            BasketbolcuB7.setVisible(false);
            SkorB.setText(Integer.toString(Oyuncu.SkorGoster("basketbol",6,SecilenPozisyon.getText())));
        }
        else if (R4=="4") {
            OrtayaK2.setIcon(BasketbolcuB4.getIcon());
            OrtayaK2.setVisible(true);
            BasketbolcuB4.setVisible(false);
            BasketbolcuB8.setVisible(false);
            SkorB.setText(Integer.toString(Oyuncu.SkorGoster("basketbol",7,SecilenPozisyon.getText())));
        }
        if(Integer.valueOf(SkorK.getText())<Integer.valueOf(SkorB.getText())){
            puan2=puan2+10;
        }  
        else if(Integer.valueOf(SkorK.getText())>Integer.valueOf(SkorB.getText())){
            puan1=puan1+10;
        }
        PuanK.setText(Integer.toString(puan1));
        PuanB.setText(Integer.toString(puan2));
        if(tik==8 && puan1<puan2)
        {
            JOptionPane.showMessageDialog(null,KullaniciLabeli.getText()+" Skor: "+Integer.toString(puan1)+"\n"+"Bilgisayar Skor: "+Integer.toString(puan2), "Bilgisayar Kazandı!" , JOptionPane.INFORMATION_MESSAGE);
        }
        else if(tik==8 && puan1>puan2)
        {
            JOptionPane.showMessageDialog(null,KullaniciLabeli.getText()+" Skor: "+Integer.toString(puan1)+"\n"+"Bilgisayar Skor: "+Integer.toString(puan2),KullaniciLabeli.getText()+" Kazandı!" , JOptionPane.INFORMATION_MESSAGE);
            
        }
        else if(tik==8 && puan1==puan2)
        {
            JOptionPane.showMessageDialog(null,KullaniciLabeli.getText()+" Skor: "+Integer.toString(puan1)+"\n"+"Bilgisayar Skor: "+Integer.toString(puan2),"Oyun Berabere Sonuçlandı!" , JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_BasketbolcuK4ActionPerformed

    private void SecilenPozisyonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecilenPozisyonActionPerformed
        
       
    }//GEN-LAST:event_SecilenPozisyonActionPerformed

    private void SkorKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SkorKActionPerformed

    }//GEN-LAST:event_SkorKActionPerformed

    private void SkorBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SkorBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SkorBActionPerformed

    private void OrtayaK2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrtayaK2ActionPerformed
        
    }//GEN-LAST:event_OrtayaK2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void PuanKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PuanKActionPerformed
        
            
    }//GEN-LAST:event_PuanKActionPerformed

    private void PuanBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PuanBActionPerformed
       
       
    }//GEN-LAST:event_PuanBActionPerformed

    private void İsimKutusuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_İsimKutusuActionPerformed
        İsimLabeli.setVisible(false);
        İsimKutusu.setVisible(false);
        KullaniciLabeli.setText(İsimKutusu.getText());
        Başla.setEnabled(true);
    }//GEN-LAST:event_İsimKutusuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Oyun2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Oyun2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Oyun2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Oyun2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Oyun2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BasketbolcuB1;
    private javax.swing.JButton BasketbolcuB2;
    private javax.swing.JButton BasketbolcuB3;
    private javax.swing.JButton BasketbolcuB4;
    private javax.swing.JButton BasketbolcuB5;
    private javax.swing.JButton BasketbolcuB6;
    private javax.swing.JButton BasketbolcuB7;
    private javax.swing.JButton BasketbolcuB8;
    private javax.swing.JButton BasketbolcuK1;
    private javax.swing.JButton BasketbolcuK2;
    private javax.swing.JButton BasketbolcuK3;
    private javax.swing.JButton BasketbolcuK4;
    private javax.swing.JButton Başla;
    private javax.swing.JLabel BilgisayarLabeli;
    private javax.swing.JButton FutbolcuB1;
    private javax.swing.JButton FutbolcuB2;
    private javax.swing.JButton FutbolcuB3;
    private javax.swing.JButton FutbolcuB4;
    private javax.swing.JButton FutbolcuB5;
    private javax.swing.JButton FutbolcuB6;
    private javax.swing.JButton FutbolcuB7;
    private javax.swing.JButton FutbolcuB8;
    private javax.swing.JButton FutbolcuK1;
    private javax.swing.JButton FutbolcuK2;
    private javax.swing.JButton FutbolcuK3;
    private javax.swing.JButton FutbolcuK4;
    private javax.swing.JButton KapatmaTuşu;
    private javax.swing.JLabel KullaniciLabeli;
    private javax.swing.JButton OrtayaK1;
    private javax.swing.JButton OrtayaK2;
    private javax.swing.JTextField PuanB;
    private javax.swing.JTextField PuanK;
    private javax.swing.JButton SecilenPozisyon;
    private javax.swing.JTextField SkorB;
    private javax.swing.JTextField SkorK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField İsimKutusu;
    private javax.swing.JLabel İsimLabeli;
    // End of variables declaration//GEN-END:variables
}
