/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JOptionPane;

/**
 *
 * @author Mertcan
 */
public class Oyun2 extends javax.swing.JFrame {

    /**
     * Creates new form Arayüz
     */
    static String ad1,ad2,ad3,ad4,ad5,ad6,ad7,ad8;
    static String bd1,bd2,bd3,bd4,bd5,bd6,bd7,bd8;
    
    public Oyun2() {
        initComponents();
        OrtayaK1.setVisible(false);
        OrtayaK2.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        KapatmaTuşu = new javax.swing.JButton();
        FutbolcuK1 = new javax.swing.JButton();
        FutbolcuK2 = new javax.swing.JButton();
        FutbolcuK3 = new javax.swing.JButton();
        FutbolcuK4 = new javax.swing.JButton();
        FutbolcuB4 = new javax.swing.JButton();
        FutbolcuB3 = new javax.swing.JButton();
        FutbolcuB2 = new javax.swing.JButton();
        FutbolcuB1 = new javax.swing.JButton();
        BasketbolcuK1 = new javax.swing.JButton();
        BasketbolcuK2 = new javax.swing.JButton();
        BasketbolcuK3 = new javax.swing.JButton();
        BasketbolcuK4 = new javax.swing.JButton();
        BasketbolcuB1 = new javax.swing.JButton();
        BasketbolcuB2 = new javax.swing.JButton();
        BasketbolcuB3 = new javax.swing.JButton();
        BasketbolcuB4 = new javax.swing.JButton();
        OrtayaK1 = new javax.swing.JButton();
        OrtayaK2 = new javax.swing.JButton();
        Başla = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        KapatmaTuşu.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mertcan\\Desktop\\sonlar\\kapatma tuşu.png")); // NOI18N
        KapatmaTuşu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KapatmaTuşuActionPerformed(evt);
            }
        });
        getContentPane().add(KapatmaTuşu);
        KapatmaTuşu.setBounds(1340, 20, 10, 10);

        FutbolcuK1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mertcan\\Desktop\\sonlar\\futbolcukartıarkasıson.png")); // NOI18N
        FutbolcuK1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FutbolcuK1ActionPerformed(evt);
            }
        });
        getContentPane().add(FutbolcuK1);
        FutbolcuK1.setBounds(40, 330, 120, 200);

        FutbolcuK2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mertcan\\Desktop\\sonlar\\futbolcukartıarkasıson.png")); // NOI18N
        FutbolcuK2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FutbolcuK2ActionPerformed(evt);
            }
        });
        getContentPane().add(FutbolcuK2);
        FutbolcuK2.setBounds(170, 330, 120, 200);

        FutbolcuK3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mertcan\\Desktop\\sonlar\\futbolcukartıarkasıson.png")); // NOI18N
        FutbolcuK3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FutbolcuK3ActionPerformed(evt);
            }
        });
        getContentPane().add(FutbolcuK3);
        FutbolcuK3.setBounds(300, 330, 120, 200);

        FutbolcuK4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mertcan\\Desktop\\sonlar\\futbolcukartıarkasıson.png")); // NOI18N
        FutbolcuK4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FutbolcuK4ActionPerformed(evt);
            }
        });
        getContentPane().add(FutbolcuK4);
        FutbolcuK4.setBounds(430, 330, 120, 200);

        FutbolcuB4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mertcan\\Desktop\\sonlar\\futbolcukartıarkasıson.png")); // NOI18N
        getContentPane().add(FutbolcuB4);
        FutbolcuB4.setBounds(1190, 330, 120, 200);

        FutbolcuB3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mertcan\\Desktop\\sonlar\\futbolcukartıarkasıson.png")); // NOI18N
        getContentPane().add(FutbolcuB3);
        FutbolcuB3.setBounds(1060, 330, 120, 200);

        FutbolcuB2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mertcan\\Desktop\\sonlar\\futbolcukartıarkasıson.png")); // NOI18N
        getContentPane().add(FutbolcuB2);
        FutbolcuB2.setBounds(930, 330, 120, 200);

        FutbolcuB1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mertcan\\Desktop\\sonlar\\futbolcukartıarkasıson.png")); // NOI18N
        getContentPane().add(FutbolcuB1);
        FutbolcuB1.setBounds(800, 330, 120, 200);

        BasketbolcuK1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mertcan\\Desktop\\sonlar\\basketkartarkason.png")); // NOI18N
        BasketbolcuK1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BasketbolcuK1ActionPerformed(evt);
            }
        });
        getContentPane().add(BasketbolcuK1);
        BasketbolcuK1.setBounds(40, 540, 120, 200);

        BasketbolcuK2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mertcan\\Desktop\\sonlar\\basketkartarkason.png")); // NOI18N
        BasketbolcuK2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BasketbolcuK2ActionPerformed(evt);
            }
        });
        getContentPane().add(BasketbolcuK2);
        BasketbolcuK2.setBounds(170, 540, 120, 200);

        BasketbolcuK3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mertcan\\Desktop\\sonlar\\basketkartarkason.png")); // NOI18N
        BasketbolcuK3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BasketbolcuK3ActionPerformed(evt);
            }
        });
        getContentPane().add(BasketbolcuK3);
        BasketbolcuK3.setBounds(300, 540, 120, 200);

        BasketbolcuK4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mertcan\\Desktop\\sonlar\\basketkartarkason.png")); // NOI18N
        BasketbolcuK4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BasketbolcuK4ActionPerformed(evt);
            }
        });
        getContentPane().add(BasketbolcuK4);
        BasketbolcuK4.setBounds(430, 540, 120, 200);

        BasketbolcuB1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mertcan\\Desktop\\sonlar\\basketkartarkason.png")); // NOI18N
        getContentPane().add(BasketbolcuB1);
        BasketbolcuB1.setBounds(800, 540, 120, 200);

        BasketbolcuB2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mertcan\\Desktop\\sonlar\\basketkartarkason.png")); // NOI18N
        getContentPane().add(BasketbolcuB2);
        BasketbolcuB2.setBounds(930, 540, 120, 200);

        BasketbolcuB3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mertcan\\Desktop\\sonlar\\basketkartarkason.png")); // NOI18N
        getContentPane().add(BasketbolcuB3);
        BasketbolcuB3.setBounds(1060, 540, 120, 200);

        BasketbolcuB4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mertcan\\Desktop\\sonlar\\basketkartarkason.png")); // NOI18N
        getContentPane().add(BasketbolcuB4);
        BasketbolcuB4.setBounds(1190, 540, 120, 200);
        getContentPane().add(OrtayaK1);
        OrtayaK1.setBounds(440, 110, 120, 200);
        getContentPane().add(OrtayaK2);
        OrtayaK2.setBounds(790, 110, 120, 200);

        Başla.setText("BAŞLA");
        Başla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BaşlaActionPerformed(evt);
            }
        });
        getContentPane().add(Başla);
        Başla.setBounds(610, 240, 110, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mertcan\\Desktop\\sonlar\\2.ekran.jpeg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1370, 770);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1370, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1370, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KapatmaTuşuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KapatmaTuşuActionPerformed
        // TODO add your handling code here:
        int sonuc = JOptionPane.showConfirmDialog(null,
                "Kapatmak İstediğinize Emin Misiniz?",
                "Uyarı",
                JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (sonuc == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_KapatmaTuşuActionPerformed

    private void BaşlaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BaşlaActionPerformed
        // TODO add your handling code here:
       Başla.setVisible(false);
       ArrayList<String> yenilist = new ArrayList<String>();
       yenilist.add(ad1);
       yenilist.add(ad2);
       yenilist.add(ad3);
       yenilist.add(ad4);
       yenilist.add(ad5);
       yenilist.add(ad6);
       yenilist.add(ad7);
       yenilist.add(ad8);
       Collections.shuffle(yenilist);
       Oyuncu.a1=(yenilist.get(0));
       Oyuncu.a2=(yenilist.get(1));
       Oyuncu.a3=(yenilist.get(2));
       Oyuncu.a4=(yenilist.get(3));
       Oyuncu.a5=(yenilist.get(4));
       Oyuncu.a6=(yenilist.get(5));
       Oyuncu.a7=(yenilist.get(6));
       Oyuncu.a8=(yenilist.get(7));
       
       ArrayList<String> yenilist2 = new ArrayList<String>();
       yenilist2.add(bd1);
       yenilist2.add(bd2);
       yenilist2.add(bd3);
       yenilist2.add(bd4);
       yenilist2.add(bd5);
       yenilist2.add(bd6);
       yenilist2.add(bd7);
       yenilist2.add(bd8);
       Collections.shuffle(yenilist2);
       Oyuncu.b1=(yenilist2.get(0));
       Oyuncu.b2=(yenilist2.get(1));
       Oyuncu.b3=(yenilist2.get(2));
       Oyuncu.b4=(yenilist2.get(3));
       Oyuncu.b5=(yenilist2.get(4));
       Oyuncu.b6=(yenilist2.get(5));
       Oyuncu.b7=(yenilist2.get(6));
       Oyuncu.b8=(yenilist2.get(7));
       
       System.out.println("Kullanıcı: ");
       for(int j=0;j<=3;j++){
           System.out.println(yenilist.get(j));     
           System.out.println(yenilist2.get(j));
            } 
       for(int i=0;i<=3;i++){
           if(i==0){
           BasketbolcuK1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/" + yenilist2.get(i) + ".png")));
           BasketbolcuK2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/" + yenilist2.get(i+1) + ".png")));
           BasketbolcuK3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/" + yenilist2.get(i+2) + ".png")));
           BasketbolcuK4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/" + yenilist2.get(i+3) + ".png")));
           }}
        for(int i=4;i<=7;i++){
           if(i==4){
           BasketbolcuB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/" + yenilist2.get(i) + ".png")));
           BasketbolcuB2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/" + yenilist2.get(i+1) + ".png")));
           BasketbolcuB3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/" + yenilist2.get(i+2) + ".png")));
           BasketbolcuB4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/" + yenilist2.get(i+3) + ".png")));
           }
        }   
       System.out.println("");
       System.out.println("Bilgisayar: ");
       for(int j=4;j<=7;j++){
           System.out.println(yenilist.get(j));     
           System.out.println(yenilist2.get(j));
            } 
       for( int i=0;i<=3;i++){
           if(i==0){
           FutbolcuK1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/" + yenilist.get(i) + ".png")));
           FutbolcuK2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/" + yenilist.get(i+1) + ".png")));
           FutbolcuK3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/" + yenilist.get(i+2) + ".png")));
           FutbolcuK4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/" + yenilist.get(i+3) + ".png")));
           }}
        for(int i=4;i<=7;i++){
           if(i==4){
           FutbolcuB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/" + yenilist.get(i) + ".png")));
           FutbolcuB2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/" + yenilist.get(i+1) + ".png")));
           FutbolcuB3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/" + yenilist.get(i+2) + ".png")));
           FutbolcuB4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/" + yenilist.get(i+3) + ".png")));
           }
        }   
       
    }//GEN-LAST:event_BaşlaActionPerformed

    private void FutbolcuK1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FutbolcuK1ActionPerformed
        // TODO add your handling code here:
        OrtayaK1.setIcon(FutbolcuK1.getIcon());
        FutbolcuK1.setVisible(false);
        OrtayaK1.setVisible(true);
        
    }//GEN-LAST:event_FutbolcuK1ActionPerformed

    private void BasketbolcuK2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BasketbolcuK2ActionPerformed
        // TODO add your handling code here:
        OrtayaK1.setIcon(BasketbolcuK2.getIcon());
        BasketbolcuK2.setVisible(false);
        OrtayaK1.setVisible(true);
    }//GEN-LAST:event_BasketbolcuK2ActionPerformed

    private void FutbolcuK2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FutbolcuK2ActionPerformed
        // TODO add your handling code here:
        OrtayaK1.setIcon(FutbolcuK2.getIcon());
        FutbolcuK2.setVisible(false);
        OrtayaK1.setVisible(true);
        
    }//GEN-LAST:event_FutbolcuK2ActionPerformed

    private void FutbolcuK3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FutbolcuK3ActionPerformed
        // TODO add your handling code here:
        OrtayaK1.setIcon(FutbolcuK3.getIcon());
        FutbolcuK3.setVisible(false);
        OrtayaK1.setVisible(true);
        
    }//GEN-LAST:event_FutbolcuK3ActionPerformed

    private void FutbolcuK4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FutbolcuK4ActionPerformed
        // TODO add your handling code here:
        OrtayaK1.setIcon(FutbolcuK4.getIcon());
        FutbolcuK4.setVisible(false);
        OrtayaK1.setVisible(true);
        
    }//GEN-LAST:event_FutbolcuK4ActionPerformed

    private void BasketbolcuK1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BasketbolcuK1ActionPerformed
        // TODO add your handling code here:
        OrtayaK1.setIcon(BasketbolcuK1.getIcon());
        BasketbolcuK1.setVisible(false);
        OrtayaK1.setVisible(true);
    }//GEN-LAST:event_BasketbolcuK1ActionPerformed

    private void BasketbolcuK3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BasketbolcuK3ActionPerformed
        // TODO add your handling code here:
        OrtayaK1.setIcon(BasketbolcuK3.getIcon());
        BasketbolcuK3.setVisible(false);
        OrtayaK1.setVisible(true);
    }//GEN-LAST:event_BasketbolcuK3ActionPerformed

    private void BasketbolcuK4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BasketbolcuK4ActionPerformed
        // TODO add your handling code here:
        OrtayaK1.setIcon(BasketbolcuK4.getIcon());
        BasketbolcuK4.setVisible(false);
        OrtayaK1.setVisible(true);
    }//GEN-LAST:event_BasketbolcuK4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Oyun2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Oyun2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Oyun2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Oyun2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Oyun2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BasketbolcuB1;
    private javax.swing.JButton BasketbolcuB2;
    private javax.swing.JButton BasketbolcuB3;
    private javax.swing.JButton BasketbolcuB4;
    private javax.swing.JButton BasketbolcuK1;
    private javax.swing.JButton BasketbolcuK2;
    private javax.swing.JButton BasketbolcuK3;
    private javax.swing.JButton BasketbolcuK4;
    private javax.swing.JButton Başla;
    private javax.swing.JButton FutbolcuB1;
    private javax.swing.JButton FutbolcuB2;
    private javax.swing.JButton FutbolcuB3;
    private javax.swing.JButton FutbolcuB4;
    private javax.swing.JButton FutbolcuK1;
    private javax.swing.JButton FutbolcuK2;
    private javax.swing.JButton FutbolcuK3;
    private javax.swing.JButton FutbolcuK4;
    private javax.swing.JButton KapatmaTuşu;
    private javax.swing.JButton OrtayaK1;
    private javax.swing.JButton OrtayaK2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
